[tox]
requires =
    tox>=4
    tox-uv
env_list =
    py314
    lint

[testenv]
runner = uv-venv-lock-runner
description = run tests
allowlist_externals = uv
deps =
    pytest
commands =
    python runtests.py

[testenv:lint]
runner = uv-venv-lock-runner
description = run ruff
allowlist_externals =
    uv
    ruff
deps =
    ruff
commands =
    ruff check django_rmq tests
    ruff format --check django_rmq tests
ignore_errors = true
