[tox]
requires =
    tox>=4
    tox-uv
env_list =
    py314
    lint

[testenv]
runner = uv-venv-lock-runner
description = run tests
allowlist_externals = uv
deps =
    pytest
commands =
    python runtests.py

[testenv:lint]
runner = uv-venv-lock-runner
description = run pylint
allowlist_externals =
    uv
    pylint
deps =
    pylint
commands =
    python -m pylint django_rmq tests
ignore_errors = true
