name: Upload Django-RMQ Package

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:

  # The testing phase of a package with supported Python versions
  test:
    runs-on: self-hosted

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
      fail-fast: true

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --group dev --python ${{ matrix.python-version }}

      - name: Run tests
        run: uv run --python ${{ matrix.python-version }} pytest

  # Assemble the package (once, py3-none-any)
  release-build:
    runs-on: self-hosted
    needs: test

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install 3.10  # The build version doesn't matter which one.

      - name: Build distributions
        run: uv build

      - name: Upload distributions as artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  # Publish on PyPI
  pypi-publish:
    runs-on: self-hosted
    needs: release-build

    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/django-rmq

    steps:
      - name: Download distributions from artifact
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/