name: Upload Django-RMQ Package

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:

  # Run the full test suite (unit + integration) before publishing anything
  tests:
    uses: ./.github/workflows/ci.yml

  # Assemble the package (once, py3-none-any)
  release-build:
    runs-on: self-hosted
    needs: tests

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install 3.10  # The build version doesn't matter which one.

      - name: Build distributions
        run: uv build

      - name: Upload distributions as artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  # Publish on PyPI
  pypi-publish:
    runs-on: self-hosted
    needs: release-build

    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/django-rmq

    steps:
      - name: Download distributions from artifact
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/